### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by darwingr** [ThreeFourSeven/Database-Gui#13]
This is not a priority.

The name of the repository should be changed to something less generic.
Here's some I propose:
 - JSDB
 - JuvenileStatisticalDatabase
 - ???give it some thought

Also the description can be more specific and even a little "click-baity" because it helps other people find it or makes them want to check it out when they're looking at you're GitHub page.
For example, it looks really boring (despite how awesome it really is) on Seven's page here:
![screenshot 2018-03-29 23 13 20](https://user-images.githubusercontent.com/6166398/38121679-49ea3694-33a7-11e8-88b5-de9e7fa56b62.png)

I think aiming for a length of 2 lines of description in that box above is good.

**Comment by cynthiaforgeron** [comment]
New repository name: MRIDB
New description: Statistical and storage application for analyzing FreeSurfer-processed MRI data.
