### ISSUE TITLE
Search by measurement

### ISSUE THREAD

**Issue by mikekenn** [ThreeFourSeven/Database-Gui#20]
We should identify this as searching by the id number of the measurement.

Also, could we get the search bar added to the Filters section of the screen? Im thinking at the top, below "Filters" and above "Male" and "ADHD".

Also, we can remove the option for ADHD & Autism as we only have the 1 data set now, ADHD.

![capture](https://user-images.githubusercontent.com/17320555/38266844-1aa9ee04-3750-11e8-9ec5-26a36597f658.PNG)

**Comment by mikekenn** [comment]
@ThreeFourSeven switch out the search bars you moved around.

**Comment by darwingr** [comment]
this was completed
