### ISSUE TITLE
Changing age range inputs does not update underlying values

### ISSUE THREAD

**Issue by darwingr** [ThreeFourSeven/Database-Gui#23]
![screenshot 2018-04-03 16 11 43](https://user-images.githubusercontent.com/6166398/38270540-110be8ac-375a-11e8-9e70-ee1cc69afcc8.png)

Changing those age values on the left still seems to leave them as their initialized values in the code.

**Comment by mikekenn** [comment]
This has been fixed. @ThreeFourSeven has fixed it.
