### ISSUE TITLE
Don't know how to create tables in sqlplus

### ISSUE THREAD

**Issue by darwingr** [ThreeFourSeven/Database-Gui#3]
Once I'm logged in I get the following error whenever I try to make a table:
```
SQL> CREATE TABLE users ( id number(3), primary key (id) );
CREATE TABLE users ( id  number(3), primary key (id) )
*
ERROR at line 1:
ORA-01950: no privileges on tablespace 'USERS'
```
What do I need to do?

**Comment by mikekenn** [comment]
When i try i get the same as well. When i print out my permissions on the DB i have non. Weird.
![capture](https://user-images.githubusercontent.com/17320555/36749153-4a98cc7a-1bd0-11e8-9a02-a442ce0918e7.PNG)

**Comment by darwingr** [comment]
A couple things from class today that I haven't tried yet:
1. I think the table might need to be more specific. 
e.g. `CREATE TABLE jsdb.users ( id NUMBER(3), PRIMARY KEY (id) );`
2. The default table space needs to be set so we don't need to be this specific all the time...[Change the default table space](http://www.java2s.com/Code/Oracle/Table/Changeuserdefaulttablespaceandtemporarytablespace.htm).

**Comment by mikekenn** [comment]
Issue has been resolved.
